1. Consultar el nombre de completo de los médicos que han realizado al menos una consulta.
SELECT NOMBRE||' '||APATERNO||' '||AMATERNO AS MEDICO FROM MEDICO WHERE ID_MEDICO IN 
(SELECT ID_MEDICO FROM (SELECT ID_MEDICO,COUNT(*)AS TOTAL FROM CONSULTA GROUP BY ID_MEDICO)TMP WHERE TMP.TOTAL >= 1);

2. Consultar el nombre completo de los pacientes que han sido consultados.
SELECT P.* FROM PACIENTE P JOIN CONSULTA CO ON P.ID_PACIENTE = CO.ID_PACIENTE;

3. Consultar el nombre completo de los pacientes que han sido consultados e incluir el nombre completo del médico.
SELECT P.NOMBRE||' '||P.APATERNO||' '||P.AMATERNO AS PACIENTE,M.NOMBRE||' '||M.APATERNO||' '||M.AMATERNO AS MEDICO 
FROM PACIENTE P JOIN CONSULTA CO ON P.ID_PACIENTE = CO.ID_PACIENTE JOIN MEDICO M ON CO.ID_MEDICO = M.ID_MEDICO;

4. Consultar el nombre completo de los pacientes que han sido hospitalizados.
SELECT P.NOMBRE||' '||P.APATERNO||' '||P.AMATERNO AS PACIENTE FROM PACIENTE P JOIN HOZPITALIZACION H ON P.ID_PACIENTE = H.ID_PACIENTE;

5. Consultar el nombre completo de los pacientes y el nombre de los medicamentos que le han sido recetados.
SELECT P.NOMBRE||' '||P.APATERNO||' '||P.AMATERNO AS PACIENTE,M.NOMBRE AS MEDICAMENTO 
FROM PACIENTE P JOIN RECETA R ON P.ID_PACIENTE = R.ID_PACIENTE 
JOIN MEDICAMENTO M ON R.ID_MEDICAMENTO = M.ID_MEDICAMENTO;

6. Consultar el nombre completo de los médicos y el total de consultas que han realizado.
SELECT M.NOMBRE||' '||M.APATERNO||' '||M.AMATERNO AS MEDICO,TOTAL_CONSULTAS FROM 
(SELECT ID_MEDICO,COUNT(*) AS TOTAL_CONSULTAS FROM CONSULTA GROUP BY ID_MEDICO)TMP,MEDICO M WHERE M.ID_MEDICO = TMP.ID_MEDICO;

7. Consultar el nombre de los médicos que no han realizado consultas.
SELECT M.NOMBRE||' '||M.APATERNO||' '||M.AMATERNO AS MEDICO,TOTAL_CONSULTAS FROM 
(SELECT ID_MEDICO,COUNT(*) AS TOTAL_CONSULTAS FROM CONSULTA GROUP BY ID_MEDICO)TMP,MEDICO M 
WHERE M.ID_MEDICO = TMP.ID_MEDICO AND TMP.TOTAL_CONSULTAS = 0;

8. Consultar el nombre completo de los pacientes y el total de consultas que ha tenido cada uno.
SELECT P.NOMBRE||' '||P.APATERNO||' '||P.AMATERNO AS PACIENTE,TMP.TOTAL FROM PACIENTE P,
(SELECT ID_PACIENTE,COUNT(*) AS TOTAL FROM CONSULTA GROUP BY ID_PACIENTE)TMP WHERE P.ID_PACIENTE = TMP.ID_PACIENTE;

9. Consultar el nombre de los medicamentos que no se han recetado.
SELECT * FROM MEDICAMENTO WHERE ID_MEDICAMENTO NOT IN (SELECT ID_MEDICAMENTO FROM RECETA);

10. Consultar el nombre completo de los pacientes que más consultas han tenido.
SELECT DISTINCT P.NOMBRE||' '||P.APATERNO||' '||P.AMATERNO AS PACIENTE,TMP.TOTAL FROM PACIENTE P,
(SELECT ID_PACIENTE,COUNT(*) AS TOTAL FROM CONSULTA GROUP BY ID_PACIENTE)TMP 
WHERE P.ID_PACIENTE IN (SELECT ID_PACIENTE FROM (SELECT ID_PACIENTE,COUNT(*) AS TOTAL FROM CONSULTA GROUP BY ID_PACIENTE)TMP 
WHERE TMP.TOTAL = (SELECT MAX(TOTAL) FROM (SELECT DISTINCT ID_PACIENTE,COUNT(*) AS TOTAL FROM CONSULTA GROUP BY ID_PACIENTE)));

11. Consultar el nombre completo de los médicos que más consultas han tenido.
SELECT DISTINCT M.NOMBRE||' '||M.APATERNO||' '||M.AMATERNO AS MEDICO,TOTAL FROM MEDICO M,
(SELECT ID_MEDICO,COUNT(*) AS TOTAL FROM CONSULTA GROUP BY ID_MEDICO)TMP 
WHERE M.ID_MEDICO IN (SELECT ID_MEDICO FROM (SELECT ID_MEDICO,COUNT(*) AS TOTAL FROM CONSULTA GROUP BY ID_MEDICO)TMP 
WHERE TMP.TOTAL = (SELECT MAX(TOTAL) FROM (SELECT DISTINCT ID_MEDICO,COUNT(*) AS TOTAL FROM CONSULTA GROUP BY ID_MEDICO)));

12. Consultar el nombre completo de las enfermeras que más pacientes han atendido.
SELECT DISTINCT E.NOMBRE||' '||E.APATERNO||' '||E.AMATERNO AS MEDICO,TOTAL FROM ENFERMERA E,
(SELECT ID_ENFERMERA,COUNT(*) AS TOTAL FROM HOZPITALIZACION GROUP BY ID_ENFERMERA)TMP 
WHERE E.ID_ENFERMERA IN (SELECT ID_ENFERMERA FROM (SELECT ID_ENFERMERA,COUNT(*) AS TOTAL FROM HOZPITALIZACION GROUP BY ID_ENFERMERA)TMP 
WHERE TMP.TOTAL = (SELECT MAX(TOTAL) FROM (SELECT DISTINCT ID_ENFERMERA,COUNT(*) AS TOTAL FROM HOZPITALIZACION GROUP BY ID_ENFERMERA)));

13. Consultar el nombre completo de los pacientes que no se han realizado análisis clínicos.
SELECT NOMBRE||' '||APATERNO||' '||AMATERNO AS PACIENTE FROM PACIENTE
WHERE ID_PACIENTE NOT IN (SELECT ID_PACIENTE FROM ANALISIS_CLINICO);

14. Consultar el nombre completo de los pacientes que fueron consultados pero que no fueron hospitalizados.
SELECT NOMBRE||' '||APATERNO||' '||AMATERNO AS PACIENTE FROM PACIENTE
WHERE ID_PACIENTE IN(SELECT ID_PACIENTE FROM CONSULTA) AND ID_PACIENTE NOT IN (SELECT ID_PACIENTE FROM HOZPITALIZACION);

15. Consultar el nombre completo del médico que menos consultas ha tenido.
SELECT DISTINCT M.NOMBRE||' '||M.APATERNO||' '||M.AMATERNO AS MEDICO,TOTAL FROM MEDICO M,
(SELECT ID_MEDICO,COUNT(*) AS TOTAL FROM CONSULTA GROUP BY ID_MEDICO)TMP 
WHERE M.ID_MEDICO IN (SELECT ID_MEDICO FROM (SELECT ID_MEDICO,COUNT(*) AS TOTAL FROM CONSULTA GROUP BY ID_MEDICO)TMP 
WHERE TMP.TOTAL = (SELECT MIN(TOTAL) FROM (SELECT DISTINCT ID_MEDICO,COUNT(*) AS TOTAL FROM CONSULTA GROUP BY ID_MEDICO)));
