--1. CONSULTAR LAS DIRECCIONES DE TODOS LOS ALMACENES
SELECT AL.*,D.* FROM ALMACENES AL JOIN DIRECCIONES D ON AL.ID_DIRECCION = D.ID_DIRECCION;

--2. CONSULTAR EL NOMBRE DEL CLIENTE QUE A COMPRADO "Gansito"
SELECT DISTINCT CL.* FROM CLIENTES CL JOIN CARRITO_DE CD ON CL.NOMBRE_USUARIO = CD.NOMBRE_USUARIO
JOIN CARROS_COMPRAS CC ON CD.ID_CARRO_COMPRA = CC.ID_CARRO_COMPRA JOIN CONTIENE CO 
ON CC.ID_CARRO_COMPRA = CO.ID_CARRO_COMPRA JOIN PRODUCTOS P ON CO.CODIGO = (SELECT CODIGO FROM PRODUCTOS WHERE NOMBRE = 'Gansito');

--3. CONSULTAR LOS CLIENTES QUE TENGAN COMO DIRECCION EL CODIGO POSTAL 99200
SELECT CL.* FROM CLIENTES CL JOIN CLIENTE_DIRECCIONES CD ON CL.NOMBRE_USUARIO = CD.NOMBRE_USUARIO
JOIN DIRECCIONES D ON CD.ID_DIRECCION = D.ID_DIRECCION AND D.ID_DIRECCION IN (SELECT ID_DIRECCION FROM DIRECCIONES WHERE CODIGO_POSTAL = 99200);

--4. CONSULTAR LA DIRECCION DEL ALMACEN 4
SELECT * FROM DIRECCIONES WHERE ID_DIRECCION = (SELECT ID_DIRECCION FROM ALMACENES WHERE NOMBRE = 'ALMACEN 4');

--5. CONSULTAR EL NOMBRE DE USUARIO, NOMBRE Y APELLIDO DEL CLIENTE CON EL E-MAIL "pascual@gmail.com"
SELECT NOMBRE_USUARIO,NOMBRE,APELLIDO FROM CLIENTES WHERE EMAIL = 'pascual@gmail.com';

--6. CONSULTAR EL ESTADO DE LA DIRECCION DEL CLIENTE CON NOMBRE "Pascual" Y APELLIDO "Bonilla"
SELECT DISTINCT CL.NOMBRE||' '||APELLIDO AS NOMBRE,D.ESTADO FROM DIRECCIONES D JOIN CLIENTE_DIRECCIONES CD ON D.ID_DIRECCION = CD.ID_DIRECCION
JOIN CLIENTES CL ON CL.NOMBRE_USUARIO = (SELECT NOMBRE_USUARIO FROM CLIENTES WHERE NOMBRE = 'Pascual' AND APELLIDO = 'Bonilla');

--7. CONSULTAR LA DESCRIPCION DE LA CATEGORIA A LA QUE PERTENECE EL PRODUCTO "Gansito"
SELECT DISTINCT P.NOMBRE AS PRODUCTO, CA.DESCRIPCION AS DESCRIPCION_CATEGORIA FROM CATEGORIAS CA JOIN PERTENECE PE ON CA.NOMBRE = PE.NOMBRE
JOIN PRODUCTOS P ON PE.CODIGO = P.CODIGO AND P.CODIGO = (SELECT CODIGO FROM PRODUCTOS WHERE NOMBRE = 'Gansito');

--8. CONSULTAR EL PRECIO DE LOS PRODUCTOS COMPRADOS POR EL CLIENTE CON NOMBRE DE USUARIO "jaunito1"
SELECT CL.NOMBRE AS CLIENTE,P.NOMBRE,P.PRECIO FROM PRODUCTOS P JOIN CONTIENE CO ON P.CODIGO = CO.CODIGO
JOIN CARROS_COMPRAS CC ON CO.ID_CARRO_COMPRA = CC.ID_CARRO_COMPRA
JOIN CARRITO_DE CD ON CC.ID_CARRO_COMPRA = CD.ID_CARRO_COMPRA
JOIN CLIENTES CL ON CD.NOMBRE_USUARIO = CL.NOMBRE_USUARIO AND CL.NOMBRE_USUARIO = 'jaunito1';

--9. CONSULTAR LOS PRODCUTOS ALMACENADOS EN "ALMACEN 4"
SELECT AL.NOMBRE AS ALMACEN, P.NOMBRE AS PRODUCTO FROM ALMACENES AL JOIN ALMACENA ALM ON AL.ID_ALMACEN = ALM.ID_ALMACEN
JOIN PRODUCTOS P ON ALM.CODIGO = P.CODIGO AND AL.NOMBRE = 'ALMACEN 4';

--10. CONSULTAR LAS DIRECCIONES DE TODOS LOS CLIENTES
SELECT CL.NOMBRE AS CLIENTE,D.* FROM DIRECCIONES D JOIN CLIENTE_DIRECCIONES CD ON D.ID_DIRECCION = CD.ID_DIRECCION
JOIN CLIENTES CL ON CD.NOMBRE_USUARIO = CL.NOMBRE_USUARIO;

--11. CONSULTAR LOS PRODUCTOS QUE PERTENECEN A LA CATEGORIA "Comestibles"
SELECT P.* FROM PRODUCTOS P JOIN PERTENECE PE ON P.CODIGO = PE.CODIGO
JOIN CATEGORIAS CA ON PE.NOMBRE = CA.NOMBRE AND CA.NOMBRE = 'Comestibles';

--12. CONSULTAR LOS DATOS DEL CLIENTE CON LA DIRECCION (MUNICIPIO = VALPARAÍSO, COLONIA = ALAMEDA, NUM_EXTERNO = 125
SELECT CL.* FROM CLIENTES CL JOIN CLIENTE_DIRECCIONES CD ON CL.NOMBRE_USUARIO = CD.NOMBRE_USUARIO
JOIN DIRECCIONES D ON CD.ID_DIRECCION = D.ID_DIRECCION AND D.ID_DIRECCION = 
(SELECT ID_DIRECCION FROM DIRECCIONES WHERE MUNICIPIO = 'VALPARAÍSO' AND COLONIA = 'ALAMEDA' AND NUM_EXTERNO = 125);

--13. CONSULTAR EL NOMBRE DEL ALMACEN EN EL QUE ESTA GUARDADO EL PRODUCTO "Pinguinos"
SELECT AL.NOMBRE FROM ALMACENES AL JOIN ALMACENA ALM ON AL.ID_ALMACEN = ALM.ID_ALMACEN
JOIN PRODUCTOS P ON ALM.CODIGO = P.CODIGO AND P.CODIGO = (SELECT CODIGO FROM PRODUCTOS WHERE NOMBRE = 'Pinguinos');

--14. CONSULTAR EL MUNICIPIO DE DONDE ESTAN LOS ALMACENES 
SELECT D.MUNICIPIO FROM DIRECCIONES D JOIN ALMACENES AL ON D.ID_DIRECCION = AL.ID_DIRECCION;

--15. CONSULTAR EL NOMBRE Y APELLIDO DE LOS CLIENTES QUE NO HAN COMPRADO NINGUN PRODUCTO
SELECT NOMBRE||' '||APELLIDO AS CLIENTE FROM CLIENTES WHERE NOMBRE_USUARIO NOT IN(SELECT NOMBRE_USUARIO FROM CARRITO_DE);

--16. CONSULTAR LOS CLIENTES QUE NO TIENEN DIRECCION
SELECT  NOMBRE||' '||APELLIDO AS CLIENTE FROM CLIENTES WHERE NOMBRE_USUARIO NOT IN(SELECT NOMBRE_USUARIO FROM CLIENTE_DIRECCIONES);

--17. CONSULTAR EL TOTAL DE DIRECCIONES QUE TIENE CADA CLIENTE
SELECT DISTINCT CL.NOMBRE||' '||CL.APELLIDO AS CLIENTE,CD.TOTAL AS TOTAL_DIRECCIONES 
FROM CLIENTES CL,(SELECT COUNT(*) AS TOTAL FROM CLIENTE_DIRECCIONES GROUP BY NOMBRE_USUARIO)CD;

--18. CONSUTLAR EL PRODUCTO MAS CARO
SELECT * FROM PRODUCTOS WHERE PRECIO = (SELECT MAX(PRECIO) FROM PRODUCTOS); 

--19. CONSULTAR EL PRODUCTO MAS VARATO
SELECT * FROM PRODUCTOS WHERE PRECIO = (SELECT MIN(PRECIO) FROM PRODUCTOS); 

--20. CONSULTAR EL CLIENTE CON MAYOR EDAD
SELECT * FROM CLIENTES WHERE EDAD = (SELECT MAX(EDAD) FROM CLIENTES);

--21. CONSULTAR EL CLIENTE CON MENOR EDAD
SELECT * FROM CLIENTES WHERE EDAD = (SELECT MIN(EDAD) FROM CLIENTES);

--22. CONSULTAR EL TOTAL DE VENTAS DE CADA PRODUCTO
SELECT P.NOMBRE AS PRODUCTO,CO.TOTAL AS TOTAL_VENTAS FROM PRODUCTOS P,(SELECT CODIGO,COUNT(*) AS TOTAL 
FROM CONTIENE GROUP BY CODIGO)CO WHERE P.CODIGO = CO.CODIGO; 

--23. CONSULTAR LA DIRECCION EN LA QUE ESTA ALMACENADO EL PRODUCTO "Jugo Manzana"
SELECT P.NOMBRE AS PRODUCTO,D.* FROM DIRECCIONES D JOIN ALMACENES AL ON D.ID_DIRECCION = AL.ID_DIRECCION
JOIN ALMACENA ALM ON AL.ID_ALMACEN = ALM.ID_ALMACEN
JOIN PRODUCTOS P ON ALM.CODIGO = P.CODIGO AND P.CODIGO = (SELECT CODIGO FROM PRODUCTOS WHERE NOMBRE = 'Jugo Manzana');

--24. CONSULTAR LOS DATOS GENERALES DE LOS PRODUCTOS Y SU CATEGORIA
SELECT P.*,CA.NOMBRE AS CATEGORIA FROM PRODUCTOS P JOIN PERTENECE PE ON P.CODIGO = PE.CODIGO
JOIN CATEGORIAS CA ON PE.NOMBRE = CA.NOMBRE;

--25. CONSULTAR LA DIRECCION DONDE ESTA ALMACENADO EL PRODUCTO CON LA CATEGORIA "Comestibles"
SELECT CA.NOMBRE AS CATEGORIA,D.* FROM DIRECCIONES D JOIN ALMACENES AL ON D.ID_DIRECCION = AL.ID_DIRECCION
JOIN ALMACENA ALM ON AL.ID_ALMACEN = ALM.ID_ALMACEN
JOIN PRODUCTOS P ON ALM.CODIGO = P.CODIGO 
JOIN PERTENECE PE ON P.CODIGO = PE.CODIGO
JOIN CATEGORIAS CA ON PE.NOMBRE = CA.NOMBRE AND CA.NOMBRE = (SELECT NOMBRE FROM CATEGORIAS WHERE NOMBRE = 'No empaquetados');