--1. ELIMINAR EL PRODUCTO CON NOMBRE "Coca-Cola" DEL LOS ALMACENES
DELETE FROM ALMACENA WHERE CODIGO = (SELECT CODIGO FROM PRODUCTOS WHERE NOMBRE = 'Coca-Cola');

--2. ELIMINAR CATEGORIAS DEL PRODUCTO "Doritos"
DELETE FROM PERTENECE WHERE CODIGO = (SELECT CODIGO FROM PRODUCTOS WHERE NOMBRE = 'Doritos');

--3. ELIMINAR LA LA RELACION QUE EXISTE ENTRE LOS PRODUCTOS Y LA CATEGORIA "Panes"
DELETE FROM PERTENECE WHERE NOMBRE = (SELECT NOMBRE FROM CATEGORIAS WHERE NOMBRE = 'Panes');

--4. ELIMINAR LA RELACION DE LOS ALMACENES QUE TENGAN COMO NOMBRE "ALMACEN 3"
DELETE FROM ALMACENA WHERE ID_ALMACEN = (SELECT ID_ALMACEN FROM ALMACENES WHERE NOMBRE = 'ALMACEN 3');

--5. ELIMINAR EL ALMACEN 2
DELETE FROM ALMACENES WHERE NOMBRE = 'ALMACEN 2';

--6. ELIMINAR LA DIRECCION CON LA COLONIA "ZAPATA" Y EL NUMERO EXTERNO 200
DELETE FROM DIRECCIONES WHERE COLONIA = 'ZAPATA' AND NUM_EXTERNO = 200;

--7. ELIMINAR EL CLIENTE CON EL NOMBRE FERNANDO Y EL APELLIDO ESCALANTE
DELETE FROM CLIENTES WHERE NOMBRE = 'FERNANDO' AND APELLIDO = 'ESCALANTE';

--8. ELIMINAR EL PRODUCTO DE LA MARCA "ELECTROLIT" Y CON EL NOMBRE "SUERO COCO"
DELETE FROM PRODUCTOS WHERE MARCA = 'ELECTROLIT' AND NOMBRE = 'SUERO COCO';

--9. ELIMINAR LA CATEGORIA DE "FRUTAS Y VERDURAS"
DELETE FROM CATEGORIAS WHERE NOMBRE = 'FRUTAS Y VERDURAS';

--10. ELIMINAR LA RELACION ENTRE EL CARRO 1 Y LOS CLIENTES
DELETE FROM CARRITO_DE WHERE ID_CARRO_COMPRA = 1;




