--1. MODIFICAR EL NOMBRE DEL ALMACEN 1 A ALMACEN 6
UPDATE ALMACENES SET NOMBRE ='ALMACEN 6' WHERE NOMBRE='ALMACEN 1';

--2. MODIFICAR EL NOMBRE DEL CLIENTE mArIa34
UPDATE CLIENTES SET NOMBRE='Fernanda' WHERE NOMBRE_USUARIO = 'mArIa34';

--3. MODIFICAR EL NOMBRE DEL PRODUCTO CON EL CODIGO 5DG35SJ57SJ4
UPDATE PRODUCTOS SET NOMBRE='Doritos' WHERE CODIGO='A3H2J4H2H3J2';

--4. MODIFICAR LA EDAD DEL USUARIO QUE SE LLAMA Juan
UPDATE CLIENTES SET EDAD=21 WHERE NOMBRE = 'Juan';

--5. MODIFICAR EL NUMERO INTERNO DE LA DIRECCION 1
UPDATE DIRECCIONES SET NUM_INTERNO=11 WHERE ID_DIRECCION=1;

--6. MODIFICAR LA CANTIDAD DE PRODUCTO ALMACENADO CON NOMBRE "Coca-Cola"
UPDATE ALMACENA SET CANTIDAD = 599 WHERE CODIGO = (SELECT CODIGO FROM PRODUCTOS WHERE NOMBRE = 'Coca-Cola');

--7. MODIFICAR LA DESCRIPCION DE LA CATEGORIA CON EL NOMBRE "Comestibles"
UPDATE CATEGORIAS SET DESCRIPCION = 'Todo tipo de frituras' WHERE NOMBRE = 'Comestibles';

--8. MODIFICAR LA CONTRASEÑA DEL CLIENTE CON EL NOMBRE "Pedro" Y APELLIDOS "Gonzalez"
UPDATE CLIENTES SET CONTRASENIA = 'NVU83IGC8WI29' WHERE NOMBRE = 'Pedro' AND APELLIDO = 'Gonzalez';

--9. MODIFICAR LA DIRECCION DEL ALMACEN CON NOMBRE "ALMACEN 3"
UPDATE ALMACENES SET ID_DIRECCION = 4 WHERE NOMBRE = 'ALMACEN 3';

--10. MODIFICAR EL MUNICIPIO, COLONIA, NUM_EXTERNO Y NUM_INTERNO DEL MUNICIPIO CON MUNICIPIO = "VALPARAÍSO", COLONIA = "ATOTONILCO", NUM_EXTERNO = 101
UPDATE DIRECCIONES SET MUNICIPIO = 'JEREZ',COLONIA = 'CENTRO',NUM_EXTERNO = 222,NUM_INTERNO = 24 
WHERE MUNICIPIO = 'VALPARAÍSO' AND COLONIA = 'ATOTONILCO' AND NUM_EXTERNO = 101;

