CREATE TABLE DIRECCIONES(
  ID_DIRECCION NUMBER(8) CONSTRAINT DIRECCION_PK PRIMARY KEY,
  CODIGO_POSTAL NUMBER(5) CONSTRAINT DIR_COD_POS_NN NOT NULL,
  ESTADO VARCHAR(100) CONSTRAINT DIR_EST_NN NOT NULL,
  MUNICIPIO VARCHAR(100) CONSTRAINT DIR_MUN_NN NOT NULL,
  COLONIA VARCHAR(100) CONSTRAINT DIR_COL_NN NOT NULL,
  NUM_EXTERNO NUMBER(4) CONSTRAINT DIR_NUM_EXT_NN NOT NULL,
  NUM_INTERNO NUMBER(4)
);

CREATE TABLE CLIENTES(
  NOMBRE_USUARIO VARCHAR(50) CONSTRAINT CLIENTE_PK PRIMARY KEY,
  CONTRASENIA VARCHAR(50) CONSTRAINT CLI_CON_NN NOT NULL,
  NOMBRE VARCHAR(50) CONSTRAINT CLI_NOM_NN NOT NULL,
  APELLIDO VARCHAR(100) CONSTRAINT CLI_APE_NN NOT NULL,
  EDAD NUMBER(2),
  EMAIL VARCHAR(150) CONSTRAINT CLI_EM_NN NOT NULL
);

CREATE TABLE CLIENTE_DIRECCIONES(
  NOMBRE_USUARIO VARCHAR(50),
  ID_DIRECCION NUMBER(8),
  CONSTRAINT CLI_DIR_PK PRIMARY KEY (NOMBRE_USUARIO,ID_DIRECCION),
  CONSTRAINT CLI_CLI_DIR_FK FOREIGN KEY (NOMBRE_USUARIO) REFERENCES CLIENTES(NOMBRE_USUARIO),
  CONSTRAINT DIR_CLI_DIR_FK FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCIONES(ID_DIRECCION)
);

CREATE TABLE ALMACENES(
  ID_ALMACEN NUMBER(5) CONSTRAINT ALMACENES_PK PRIMARY KEY,
  NOMBRE VARCHAR(100) CONSTRAINT ALM_NOM_NN NOT NULL,
  ID_DIRECCION NUMBER(8) CONSTRAINT ALM_DIR_NN NOT NULL,
  CONSTRAINT DIR_ALM_FK FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCIONES(ID_DIRECCION)
);

CREATE TABLE PRODUCTOS(
  CODIGO CHAR(12) CONSTRAINT PRODUCTO_PK PRIMARY KEY,
  MARCA VARCHAR(50) CONSTRAINT PRO_MAR_NN NOT NULL,
  NOMBRE VARCHAR(100) CONSTRAINT PRO_NOM_NN NOT NULL,
  DESCRIPCION VARCHAR(150),
  PRECIO NUMBER(7,2) CONSTRAINT PRO_PRE_NN NOT NULL
);

CREATE TABLE ALMACENA(
  ID_ALMACEN NUMBER(5),
  CODIGO CHAR(12),
  CANTIDAD NUMBER(5) CONSTRAINT ALM_CAN_NN NOT NULL,
  CONSTRAINT ALMACENA_PK PRIMARY KEY (ID_ALMACEN,CODIGO),
  CONSTRAINT ALM_ALM_FK FOREIGN KEY (ID_ALMACEN) REFERENCES ALMACENES(ID_ALMACEN),
  CONSTRAINT PRO_ALM_FK FOREIGN KEY (CODIGO) REFERENCES PRODUCTOS(CODIGO)
);

CREATE TABLE CATEGORIAS(
  NOMBRE VARCHAR(50) CONSTRAINT CATEGORIA_PK PRIMARY KEY,
  DESCRIPCION VARCHAR(150) CONSTRAINT CAT_DES_NN NOT NULL
);

CREATE TABLE PERTENECE(
  NOMBRE VARCHAR(50),
  CODIGO CHAR(12),
  CONSTRAINT PERTENECE_PK PRIMARY KEY (NOMBRE,CODIGO),
  CONSTRAINT CAT_PER_FK FOREIGN KEY (NOMBRE) REFERENCES CATEGORIAS(NOMBRE),
  CONSTRAINT PRO_PER_FK FOREIGN KEY (CODIGO) REFERENCES PRODUCTOS(CODIGO)
);

CREATE TABLE CARROS_COMPRAS(
  ID_CARRO_COMPRA NUMBER(5) CONSTRAINT CARRO_COMPRA_PK PRIMARY KEY
);

CREATE TABLE CONTIENE(
  CODIGO CHAR(12),
  ID_CARRO_COMPRA NUMBER(5),
  CONSTRAINT CONTIENE_PK PRIMARY KEY (CODIGO,ID_CARRO_COMPRA),
  CONSTRAINT PRO_CON_FK FOREIGN KEY (CODIGO) REFERENCES PRODUCTOS(CODIGO),
  CONSTRAINT CARR_COM_CON_FK FOREIGN KEY (ID_CARRO_COMPRA) REFERENCES CARROS_COMPRAS(ID_CARRO_COMPRA)
);

CREATE TABLE CARRITO_DE(
  NOMBRE_USUARIO VARCHAR(50),
  ID_CARRO_COMPRA NUMBER(5),
  FECHA DATE,
  CONSTRAINT CARRITO_DE_PK PRIMARY KEY (NOMBRE_USUARIO,ID_CARRO_COMPRA,FECHA),
  CONSTRAINT CLI_CARR_FK FOREIGN KEY (NOMBRE_USUARIO) REFERENCES CLIENTES(NOMBRE_USUARIO),
  CONSTRAINT CARR_COM_CARR_FK FOREIGN KEY (ID_CARRO_COMPRA) REFERENCES CARROS_COMPRAS(ID_CARRO_COMPRA)
);





